services:
  commandbox:
    image: ortussolutions/commandbox:boxlang
    ports:
      - 4080:8080
    volumes:
      - ../:/app
    networks:
      - net
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      # persist data so we don't lose our tables!
      - mysql-data:/var/lib/mysql
    networks:
      - net

networks:
  net:
  
volumes:
  mysql-data:  # Define the named volume here