services:
  commandbox:
    image: ortussolutions/commandbox:lucee5
    ports:
      - 4080:8080
    volumes:
      - ../:/app
    networks:
      - net
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - net

networks:
  net: