name: Build Release

on:
  push:
    branches:
      - master
      - main

env:
  DOCKER_IMAGE_NAME: app
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  migrations:
    name: Run Migrations
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@main

      - name: Run Migrations
        env:
            DB_CLASS: ${{ vars.DB_CLASS }}
            DB_BUNDLENAME: ${{ vars.DB_BUNDLENAME }}
            DB_BUNDLEVERSION: ${{ vars.DB_BUNDLEVERSION }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_CONNECTIONSTRING: ${{ secrets.DB_CONNECTIONSTRING }}
        run: |
          box install commandbox-migrations

          box migrate install

          box migrate up --verbose
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: migrations
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup vars
        id: vars
        run: |
          lcased=$(echo "${{ github.repository }}" | tr "[:upper:]" "[:lower:]")

          branch="${{ github.head_ref || github.ref_name }}"
          branch_tag=$(echo "$branch" | tr "[:upper:]" "[:lower:]" | sed -r 's/[^a-z0-9]/_/g' )
          tags="ghcr.io/$lcased/${{ env.DOCKER_IMAGE_NAME }}:$branch_tag"

          if [ "$branch" = "main" ]; then
            tags+=",ghcr.io/$lcased/${{ env.DOCKER_IMAGE_NAME }}:latest"
            tags+=",ghcr.io/$lcased/${{ env.DOCKER_IMAGE_NAME }}:production"
          fi

          if [ "$branch" = "develop" ]; then
            tags+=",ghcr.io/$lcased/${{ env.DOCKER_IMAGE_NAME }}:staging"
          fi

          echo "tags=$tags" >> "$GITHUB_OUTPUT" 

          rm .env.example        

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@main

      - name: Build App
        run: |
          box install --production

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Github Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: publisher
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          # Disabling provenance check due to https://community.fly.io/t/images-built-with-the-latest-docker-buildx-and-or-github-actions-work-again/10816
          provenance: false
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: .github/build/Dockerfile
          tags: ${{ steps.vars.outputs.tags }}
          push: true
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: MySessionName

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ./.github/build/task-definition.json
          desired-count: 1
          service: Workshop-FortuneCookieApp-service-2c2du44x
          cluster: fortunecookie
          wait-for-service-stability: true
